<?php
// Variables
return [
  'creatorName' => 'Supernata',
  'creatorUrl' => 'https://Supernata.id',
  'templateName' => 'SUPERNATA',
  'templateSuffix' => 'Management System',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'Karang Taruna Supernata Management System',
  'templateKeyword' => 'Supernata, management, dashboard',
  'licenseUrl' => 'https://Supernata.id/',
  'livePreview' => 'https://Supernata.id/',
  'productPage' => 'https://Supernata.id/',
  'support' => 'https://Supernata.id/',
  'moreThemes' => 'https://1.envato.market/pixinvent_portfolio',
  'documentation' => 'https://demos.pixinvent.com/vuexy-html-admin-template/documentation',
  'generator' => '',
  'changelog' => 'https://demos.pixinvent.com/vuexy/changelog.html',
  'repository' => 'https://github.com/pixinvent/vuexy-html-admin-template',
  'gitRepo' => 'pixinvent',
  'gitRepoAccess' => 'vuexy-html-admin-template',
  'githubFreeUrl' => 'https://tools.pixinvent.com/github/github-access',
  'facebookUrl' => 'https://www.facebook.com/pixinvents/',
  'twitterUrl' => 'https://twitter.com/pixinvents',
  'githubUrl' => 'https://github.com/pixinvent',
  'dribbbleUrl' => 'https://dribbble.com/pixinvent',
  'instagramUrl' => 'https://www.instagram.com/pixinvents/',
];
